export const FETCH_DATA = 'FETCH_DATA'
export const FETCH_DATA_PENDING = 'FETCH_DATA_PENDING'
export const FETCH_DATA_FULFILLED = 'FETCH_DATA_FULFILLED'
export const FETCH_DATA_REJECTED = 'FETCH_DATA_REJECTED'


export const FETCH_TRANSACTIONS = 'FETCH_TRANSACTIONS'
export const FETCH_TRANSACTIONS_PENDING = 'FETCH_TRANSACTIONS_PENDING'
export const FETCH_TRANSACTIONS_FULFILLED = 'FETCH_TRANSACTIONS_FULFILLED'
export const FETCH_TRANSACTIONS_REJECTED = 'FETCH_TRANSACTIONS_REJECTED'